### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by swenzel** [gregsexton/gtd#2]
Hey there,

I set up gtd as a tea timer.
Turns out there is a unicode sign for hot beverage (U+2615) so I tried:
`echo -e "\xe2\x98\x95 Tea is ready!" | gtd`
But it is not properly displayed :(

Cheers
Swen

**Comment by gregsexton** [comment]
Hi! Sorry this took me so long to get to. You say it's not properly displayed. Can you describe what is displayed? Do you get a square instead? Do other symbols outside of ASCII or latin-1 display properly? I think it might be the font lacking support for the U+2615 symbol.

**Comment by swenzel** [comment]
I'm getting `â` followed by two squares. However in the console it shows up properly.
Guess the gtd-server decodes the message as latin-1 then.

**Comment by gregsexton** [comment]
I've dug in to this and gtd is doing the right thing. When I run it, I get a square which is the symbol usually used to represent a missing glyph. The font used by gtd is Arial. When I changed it to DejaVu (a font with a large glyph set) it works fine and I see the tea cup symbol.

I think it must be something in your environment that is causing this to fail. What OS are you running this on?

**Comment by gregsexton** [comment]
Try this: `echo 'Ɠ'|gtd`. (I just chose the symbol randomly.) For me this works fine as Arial has this glyph and it's certainly outside of ASCII.

**Comment by swenzel** [comment]
Yes it is an environment thing... turns out java bases its charset on the locale and falls back on utf-8 only if it doesn't find anything. I'm running Ubuntu 14.04 x64.
Starting the server with `java -Dfile.encoding="utf-8" -jar gtd-server` solved it for me.
Thanks for looking into this :)

**Comment by gregsexton** [comment]
Glad you figured it out! :)
